name: build
on: 
  push:
    branches: ['*']
  pull_request:
    types: [opened, synchronize, reopened]

env:
  DOTNET_NOLOGO: true
  MSBUILDDISABLENODEREUSE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v2
      - name: ⚙ dotnet 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: 🙏 build
        run: dotnet build
      - name: 🚀 sleet
        if: ${{ !github.event.pull_request.head.repo.fork }}
        run: |
          dotnet tool install -g --version 3.2.0 sleet 
          sleet push bin --config none -f --verbose -p "SLEET_FEED_CONTAINER=nuget" -p "SLEET_FEED_CONNECTIONSTRING=${{ secrets.SLEET_CONNECTION }}" -p "SLEET_FEED_TYPE=azure"