name: release
on:
  release:
    types: [created]

env:
  DOTNET_NOLOGO: true
  MSBUILDDISABLENODEREUSE: 1

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v2
      - name: ⚙ dotnet 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: 🙏 build
        run: dotnet build -p:version=${GITHUB_REF#refs/*/v}
      - name: 🚀 push
        run: dotnet nuget push ./bin/**/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate